export const FETCH_SELLER_PRODUCTS_REQUEST = "FETCH_SELLER_PRODUCTS_REQUEST";
export const FETCH_SELLER_PRODUCTS_SUCCESS = "FETCH_SELLER_PRODUCTS_SUCCESS";
export const FETCH_SELLER_PRODUCTS_FAILURE = "FETCH_SELLER_PRODUCTS_FAILURE";

export const ADD_SELLER_PRODUCT_REQUEST = "ADD_SELLER_PRODUCT_REQUEST";
export const ADD_SELLER_PRODUCT_SUCCESS = "ADD_SELLER_PRODUCT_SUCCESS";
export const ADD_SELLER_PRODUCT_FAILURE = "ADD_SELLER_PRODUCT_FAILURE";

export const EDIT_SELLER_PRODUCT_REQUEST = "EDIT_SELLER_PRODUCT_REQUEST";
export const EDIT_SELLER_PRODUCT_SUCCESS = "EDIT_SELLER_PRODUCT_SUCCESS";
export const EDIT_SELLER_PRODUCT_FAILURE = "EDIT_SELLER_PRODUCT_FAILURE";

export const DELETE_SELLER_PRODUCT_REQUEST = "DELETE_SELLER_PRODUCT_REQUEST";
export const DELETE_SELLER_PRODUCT_SUCCESS = "DELETE_SELLER_PRODUCT_SUCCESS";
export const DELETE_SELLER_PRODUCT_FAILURE = "DELETE_SELLER_PRODUCT_FAILURE";
